name: Trivy Scan
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'  # Use 'image' to scan container images
          format: 'table'   # JSON, Table, etc.
          ignore-unfixed: true

