name: Trigger Renovate

on:
  workflow_dispatch:  # Allows for manual trigger
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight

jobs:
  renovate:
    runs-on: [self-hosted, hot-new-new]  # Use your custom runner label 'hot-new-new'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1  # Latest checkout version

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.2  # Use the latest Renovate version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Provide your GitHub token
          repositories: babywyrm/demo  # Specify the repository
          autodiscover: true
        env:
          LOG_LEVEL: debug  # Set log level to debug for detailed logs
