name: Do Renovate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  self-hosted-renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Run Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment below for automatic repository discovery
          # repositories: ''  # Leave empty for autodiscovery
          # Note: Remove `repositories` line for autodiscovery to work

