name: Trigger Renovate

on:
  workflow_dispatch:  # Allows for manual trigger
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight

jobs:
  renovate:
    runs-on: [self-hosted, hot-new-new]  # Use your custom runner label 'hot-new-new'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v39
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Provide your GitHub token
          repositories: babywyrm/demo  # Specify the repository

