name: Renovate Beta

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  renovate:
    runs-on: [self-hosted, hot-new-new]  # Use your custom runner label 'hot-new-new'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: "renovate.json"
          extraArgs: "--autodiscover"  # Enable autodiscovery of repositories
        env:
          RENOVATE_AUTODISCOVER: "true"  # Ensure the environment variable is set

