name: Trigger Renovate

on:
  # Triggers manually via the GitHub Actions UI
  workflow_dispatch:
  
  # Optionally, schedule Renovate to run periodically
  schedule:
    - cron: "0 0 * * *" # This will run every day at midnight UTC

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      # Install Node.js (includes npm and npx)
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs

      # Install Python
      - name: Install Python
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv

      # Install Ruby
      - name: Install Ruby
        run: |
          apt-get update
          apt-get install -y ruby-full

      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Install Renovate globally
      - name: Install Renovate
        run: npm install -g renovate

      # Run Renovate to update all dependencies across Node.js, Python, and Ruby
      - name: Run Renovate
        run: renovate

