  workflow_dispatch:

name: Trigger Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Optional: Run daily at midnight

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      # Install Node.js (includes npm and npx)
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -
          sudo apt-get install -y nodejs

      # Install Python
      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv

      # Install Ruby
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full

      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Install Renovate globally
      - name: Install Renovate
        run: sudo npm install -g renovate

      # Run Renovate
      - name: Run Renovate
        run: renovate

