name: Advanced Trivy Security Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      # Step 3: Run Trivy file system scan and output results in SARIF format for uploading to GitHub
      - name: Run Trivy file system scan (SARIF output)
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL --format sarif --output trivy-results.sarif .

      # Step 4: Run Trivy Docker image scan (if applicable)
      # This step is optional. You can add a specific Docker image to scan.
      - name: Run Trivy Docker image scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL my-docker-image:latest

      # Step 5: Upload Trivy scan results as an artifact for later review
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-results.sarif

      # Step 6: Fail the workflow if vulnerabilities are found
      - name: Fail the build on vulnerabilities
        run: |
          if grep -q "CRITICAL" trivy-results.sarif; then
            echo "Critical vulnerabilities found!";
            exit 1;
          else
            echo "No critical vulnerabilities found!";
          fi

