name: Full Trivy Security Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if applicable)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      # Step 3: Install Node.js dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      # Step 5: Run Trivy scan on the repository, capturing all severities
      - name: Run Trivy full scan (ALL severities)
        id: trivy-scan
        run: |
          trivy fs --exit-code 1 --severity LOW,MEDIUM,HIGH,CRITICAL --no-progress --output trivy-report.txt .
          # Print the scan results to console
          cat trivy-report.txt || echo "Trivy scan completed, but the report could not be displayed."

      # Step 6: Upload the Trivy scan results as an artifact
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt

      # Step 7: Fail the build if any HIGH or CRITICAL vulnerabilities are found
      - name: Fail on HIGH or CRITICAL vulnerabilities
        if: steps.trivy-scan.outcome == 'failure'
        run: |
          echo "High or Critical vulnerabilities found. Failing the build."

